Repository pepfar-datim/datapackr-app, pull requests merged in 2022-03, with the labels that each got.

#23 DP-483
  DESCRIPTION
  renv.lock
  server.R
Labels: enhancement

#47 Removed additional & from condition
  R/vlsTestingChart.R
Labels: bug

#44 datapackr-app v1.2.18
  .gitignore
  DESCRIPTION
  R/PSNUxIM_pivot.R
  R/comparePrioTables.R
  R/downloadDataPack.R
  R/downloadFlatPack.R
  R/downloadMemo.R
  R/evaluateIndicators.R
  R/generateComparisonTable.R
  R/getExistingPrioritization.R
  R/getMemoIndicators.R
  R/kpCascadeChart.R
  R/memoStructure.R
  R/memo_getPrioritizationTable.R
  R/modalitySummary.R
  R/preparePartnerMemoTable.R
  R/preparePrioTable.R
  R/recencyComparison.R
  R/sendDATIMExportToS3.R
  R/sendDataPacktoS3.R
  R/sendEventToS3.R
  R/sendTimeStampLogToS3.R
  R/sendValidationSummary.R
  R/subnatPyramidsChart.R
  R/updateExistingPrioritization.R
  R/utils.R
  R/validateMechanisms.R
  R/validatePSNUData.R
  R/validationSummary2.R
  R/vlsTestingChart.R
  data-raw/process_validation_rules.R
  data/cop22_validation_rules.json
  data/cop_validation_rules.rds
  manifest.json
  renv.lock
  server.R
  support_files/README
  support_files/datapack_model_data.rds
Labels: bug, enhancement

#50 Remove direct call to `updateExistingPrioritization`
  DESCRIPTION
  server.R
Labels: bug

#55 DP-564: Add sane name to output file names
  server.R
Labels: enhancement

#54 Fix Excel Bug DP-558
  DESCRIPTION
  server.R
Labels: bug
